name: CI
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            packages/typescriptlang-org/.cache
            packages/.cache
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: microsoft/playwright-github-action@v1

      # Install, should be absically instant if cached
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Verify dependencies are hooked up right
      - run: node test/verifyPackageVersions.js

      # Grab localizations
      - run: yarn docs-sync pull microsoft/TypeScript-Website-localizations#main 1

      # Build the packages
      - run: yarn bootstrap
      - run: yarn workspace typescriptlang-org build

      # Verify it compiles
      - run: yarn compile
      # Run all the package's tests
      - run: yarn test
        env:
          CI: true

      # danger for PR builds
      - if: github.event_name == 'pull_request' && github.event.base.repo.id == github.event.head.repo.id
        run: "yarn danger ci"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_DEPLOY_URL_ROOT: ${{ steps.deploy.outputs.static_web_app_url }}

      - name: "Validates that TypeScript plugins work"
        run: |
          cd ..
          npm init typescript-playground-plugin playground-my-plugin

  windows:
    runs-on: windows-latest

    steps:
      # Check out, and set up the node infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      # Get local dependencies
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      - run: yarn bootstrap
      - run: yarn build

      - name: "Validates that TypeScript plugins work"
        run: |
          cd ..
          npm init typescript-playground-plugin playground-my-plugin
