rules:
  comma-dangle: error
  comma-spacing: warn
  curly: warn
  default-case: warn
  eqeqeq: warn
  indent: [warn, 2]
  no-alert: warn
  no-console: warn
  no-debugger: warn
  no-duplicate-case: error
  no-eval: error
  no-lone-blocks: error
  no-loop-func: error
  no-multi-spaces: warn
  no-new-func: error
  no-octal: error
  no-proto: error
  no-redeclare: warn
  no-shadow-restricted-names: error
  no-sparse-arrays: error
  no-trailing-spaces: warn
  no-with: error
  quotes: [warn, single]
  semi: [warn, always]
  yoda: warn