[build]
functions = "./functions"

[[redirects]]
  from = "/year-in-review"
  to = "https://2020-year-in-review.bitsofgood.org"
  status = 301
  force = true

[[redirects]]
  from = "/bootcamp"
  to = "https://www.notion.so/gtbitsofgood/Bootcamp-b1fe164df73e42d3b9c2ab0755e4ca49"
  status = 301
  force = true

[[redirects]]
  from = "/scheduler"
  to = "https://gtbitsofgood.github.io/gt-scheduler/"
  status = 301
  force = true
  
  [[redirects]]
  from = "/blog"
  to = "https://medium.com/bits-of-good"
  status = 301
  force = true
