name: Publish to npm
on: registry_package
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: getify
      - run: npm install -g nyc@"~14.1.1" && npm install coveralls@"~3.0.6"
      - run: npm install && npm publish --@getify:registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          COVERALLS_SERVICE_NAME: github-actions
          COVERALLS_REPO_TOKEN: ${{secrets.coveralls_token}}
