name: "Test - action"

on: 
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
      - next
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: bahmutov/npm-install@v1
    - name: Build
      run: make build
    - name: Lint
      run: make lint
    - name: Unit Tests
      run: make test-unit
      env:
        CI: true

  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: bahmutov/npm-install@v1
    - name: Build
      run: make build
    - name: e2e Tests
      run: make test-e2e
      env:
        CI: true

