"""empty message

Revision ID: 5683dc4df10c
Revises: None
Create Date: 2016-03-05 21:40:45.591829

"""

# revision identifiers, used by Alembic.
revision = '5683dc4df10c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('set_id', sa.Integer, sa.ForeignKey('set.id'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    # sa.ForeignKeyConstraint(['id'], 'set_id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('box_id', sa.Integer, sa.ForeignKey('box.id'), nullable=True),
    # sa.PrimaryKeyConstraint(['id'], 'box_id')
    )
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set')
    op.drop_table('card')
    op.drop_table('box')
    ### end Alembic commands ###
