name: elegant
channels:
- conda-forge
dependencies:
- python>=3.6
- numpy>=1.17
- matplotlib>=3.1.2
- pandas>=0.25.3
- scipy>=1.3.2
- scikit-learn>=0.21.3
- scikit-image>=0.16.2
- xlrd>=1.2
- jupyter>=1.0
- sympy>=1.4
- toolz>=0.10
- pillow>=6.2
- lxml>=4.4
- networkx>=2.4
- notedown>=1.5
- beautifulsoup4>=4.8
- pip:
  # not available on conda, so use pip
  - jupytercontrib>=0.0.7
