"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fetchCancel = exports.FETCH_CANCEL = exports.fetchError = exports.FETCH_ERROR = exports.fetchEnd = exports.FETCH_END = exports.fetchStart = exports.FETCH_START = void 0;
exports.FETCH_START = 'RA/FETCH_START';
var fetchStart = function () { return ({ type: exports.FETCH_START }); };
exports.fetchStart = fetchStart;
exports.FETCH_END = 'RA/FETCH_END';
var fetchEnd = function () { return ({ type: exports.FETCH_END }); };
exports.fetchEnd = fetchEnd;
exports.FETCH_ERROR = 'RA/FETCH_ERROR';
var fetchError = function () { return ({ type: exports.FETCH_ERROR }); };
exports.fetchError = fetchError;
exports.FETCH_CANCEL = 'RA/FETCH_CANCEL';
var fetchCancel = function () { return ({ type: exports.FETCH_CANCEL }); };
exports.fetchCancel = fetchCancel;
